name: "Setup Java and Gradle Environment"
description: "Setup Java and Gradle environment for building"

inputs:
  java_version:
    description: "Java version to install"
    required: false
    default: "21"

runs:
  using: 'composite'
  steps:
    - name: Set up JDK
      uses: TimSchoenle/actions/actions/java-gradle/setup-base-environment@d5a39488dccf46d663e025f9636db1fa149e02a1 # tag=actions-java-gradle-setup-base-environment-v1.2.5
      with:
        java_version: ${{ inputs.java_version }}
