name: CI

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ '**' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  build-and-test:
    name: Build and Test (Java ${{ matrix.java_version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java_version: [ '21', '25' ]
    permissions:
      contents: read # to fetch code
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Setup Base Environment
        uses: ./.github/actions/setup-base-environment
        with:
          java_version: ${{ matrix.java_version }}

      - name: Verify Recipes and Catalog
        run: ./gradlew --no-daemon clean test :catalog:jar
