name: Cleanup Branch Caches After Deletion
on:
  delete:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions: {}

jobs:
  cleanup-caches:
    name: Cleanup Caches
    if: github.event.ref_type == 'branch'
    uses: TimSchoenle/actions/.github/workflows/maintenance-wipe-cache.yaml@c8e0a199038e53fb2514db1566cbfced02cc8a8f # workflows-maintenance-wipe-cache-v1.1.3
    permissions:
      actions: write # to delete caches
      contents: read # to list cache keys
    with:
      branch: '${{ github.event.ref }}'
      repository: '${{ github.repository }}'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
