name: Cleanup Branch Caches After Deletion
on:
  delete:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions: {}

jobs:
  cleanup-caches:
    name: Cleanup Caches
    if: github.event.ref_type == 'branch'
    uses: TimSchoenle/actions/.github/workflows/maintenance-wipe-cache.yaml@4c4d25ff76168897cdaa2fd7c81a2a8c9cee8d57 # tag=workflows-maintenance-wipe-cache-v1.1.7
    permissions:
      actions: write # to delete caches
      contents: read # to list cache keys
    with:
      branch: '${{ github.event.ref }}'
      repository: '${{ github.repository }}'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
