name: Cleanup Branch Caches After Deletion
on:
  delete:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions: {}

jobs:
  cleanup-caches:
    name: Cleanup Caches
    if: github.event.ref_type == 'branch'
    uses: TimSchoenle/actions/.github/workflows/maintenance-wipe-cache.yaml@808c4e942433c5f18a4cf51550b1d3e8b2ab7da9 # tag=workflows-maintenance-wipe-cache-v1.1.8
    permissions:
      actions: write # to delete caches
      contents: read # to list cache keys
    with:
      branch: '${{ github.event.ref }}'
      repository: '${{ github.repository }}'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
